import type { Product, Vendor, Order } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Organic Avocados',
    vendor: 'GreenLeaf Farms',
    price: 55.0,
    category: 'Produce',
    imageUrl: 'https://placehold.co/400x300.png',
    dietary: ['Organic', 'Vegan'],
    aiHint: 'avocados fruit',
  },
  {
    id: '2',
    name: 'Artisanal Sourdough',
    vendor: 'The Bread Basket',
    price: 32.5,
    category: 'Bakery',
    imageUrl: 'https://placehold.co/400x300.png',
    dietary: [],
    aiHint: 'sourdough bread',
  },
  {
    id: '3',
    name: 'Fresh Milk',
    vendor: 'DairyDelight',
    price: 20.0,
    category: 'Dairy',
    imageUrl: 'https://placehold.co/400x300.png',
    dietary: ['Organic'],
    aiHint: 'milk carton',
  },
  {
    id: '4',
    name: 'Grass-Fed Ground Beef',
    vendor: 'ButcherBox Select',
    price: 80.0,
    category: 'Meat',
    imageUrl: 'https://placehold.co/400x300.png',
    dietary: [],
    aiHint: 'ground beef',
  },
  {
    id: '5',
    name: 'Heirloom Tomatoes',
    vendor: 'GreenLeaf Farms',
    price: 45.0,
    category: 'Produce',
    imageUrl: 'https://placehold.co/400x300.png',
    dietary: ['Organic'],
    aiHint: 'tomatoes vine',
  },
  {
    id: '6',
    name: 'Imported Olive Oil',
    vendor: 'PantryPro',
    price: 60.0,
    category: 'Pantry',
    imageUrl: 'https://placehold.co/400x300.png',
    dietary: ['Vegan'],
    aiHint: 'olive oil',
  },
  {
    id: '7',
    name: 'Cheddar Cheese Block',
    vendor: 'DairyDelight',
    price: 48.0,
    category: 'Dairy',
    imageUrl: 'https://placehold.co/400x300.png',
    dietary: [],
    aiHint: 'cheese block',
  },
  {
    id: '8',
    name: 'Whole Wheat Loaf',
    vendor: 'The Bread Basket',
    price: 28.0,
    category: 'Bakery',
    imageUrl: 'https://placehold.co/400x300.png',
    dietary: [],
    aiHint: 'bread loaf',
  },
];

export const vendors: Vendor[] = [
  {
    id: '1',
    name: 'GreenLeaf Farms',
    specialty: 'Organic Produce',
    rating: 4.8,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'farm logo',
  },
  {
    id: '2',
    name: 'The Bread Basket',
    specialty: 'Artisanal Breads',
    rating: 4.9,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'bakery logo',
  },
  {
    id: '3',
    name: 'DairyDelight',
    specialty: 'Fresh Dairy Products',
    rating: 4.7,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'cow logo',
  },
  {
    id: '4',
    name: 'ButcherBox Select',
    specialty: 'Premium Meats',
    rating: 4.8,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'butcher logo',
  },
  {
    id: '5',
    name: 'PantryPro',
    specialty: 'Gourmet Pantry Staples',
    rating: 4.6,
    imageUrl: 'https://placehold.co/100x100.png',
    aiHint: 'pantry logo',
  },
];

export const orders: Order[] = [
  { id: 'ORD-001', date: '2024-07-15', total: 450.75, status: 'Delivered' },
  { id: 'ORD-002', date: '2024-07-22', total: 210.5, status: 'Shipped' },
  { id: 'ORD-003', date: '2024-07-28', total: 890.0, status: 'Processing' },
  { id: 'ORD-004', date: '2024-06-30', total: 120.0, status: 'Delivered' },
  { id: 'ORD-005', date: '2024-06-12', total: 755.25, status: 'Delivered' },
];
